export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlBlZHJvIFBhdWxpbm8iLCJlbWFpbCI6ImVtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTcwMDQwOTQwOCwiZXhwIjoxNzAxMDE0MjA4LCJhdWQiOiJVc2VycyIsImlzcyI6IkxvZ2luIiwic3ViIjoiMSJ9.AjYyAd-l1-CIlpr8eEvyDDrXxE6NaCZgyjl8NXSrHgE';
